# Generated by Django 3.0.8 on 2021-12-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(max_length=20),
        ),
    ]
